name: DEV Front End Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: git clone
        uses : actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: 14.x
      
      - name: Npm install
        run: npm install
        

      - name: Build
        run: npm run build
        
      - name: Transfer to S3 for serving static
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp\
            --recursive \
            --region ap-northeast-2
            dist s3://dguicecapstone.com
